---
# Defines deployment design and assigns role to server groups

# This play is required to gather facts from all hosts even when limiting
# Ansible to a subset of tem. When using -l or --limit in ansible-playbook,
# the default behavior is to only gather facts from these hosts which breaks
# on tasks that need facts and variables from excluded hosts.
- hosts: ceph-mons:ceph-osds:ceph-mdss:ceph-rgws
  gather_facts: false
  pre_tasks:
    - name: Gather facts from ALL hosts (regardless of limit or tags)
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      when: hostvars[item]['ansible_default_ipv4'] is not defined
      with_items: "{{ groups['all'] }}"

- hosts: ceph-mons
  become: true
  gather_facts: false
  roles:
  - ceph-mon

- hosts: ceph-osds
  become: true
  gather_facts: false
  roles:
  - ceph-osd

- hosts: ceph-mdss
  become: true
  gather_facts: false
  roles:
  - ceph-mds

- hosts: ceph-rgws
  become: true
  gather_facts: false
  roles:
  - ceph-rgw

- hosts: ceph-clients
  become: true
  gather_facts: false
  roles:
  - ceph-client
