---
- name: create ceph conf directory and assemble directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ dir_mode }}"
  with_items:
    - /etc/ceph/
    - /etc/ceph/ceph.d/

- name: "generate ceph configuration file: {{ cluster }}.conf"
  template:
    src: ceph.conf.j2
    dest: /etc/ceph/ceph.d/{{ cluster }}.conf
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ activate_file_mode }}"

- name: assemble {{ cluster }}.conf and fragments
  assemble:
    src: /etc/ceph/ceph.d/
    dest: /etc/ceph/{{ cluster }}.conf
    regexp: "^(({{cluster}})|(osd)).conf$"
    owner: "ceph"
    group: "ceph"
    mode: "0644"
  notify:
    - restart ceph mons
    - restart ceph osds
    - restart ceph mdss
    - restart ceph rgws
    - restart ceph nfss
