---
- name: create filesystem pools
  command: >
    {{ docker_exec_cmd }} --cluster {{ cluster }}
    osd pool create {{ item.name }}
    {{ item.get('pg_num', hostvars[groups[mon_group_name][0]]['osd_pool_default_pg_num']) }}
    {{ item.pgp_num | default(item.pg_num) }}
    {{ item.rule_name | default("replicated_rule") }}
    {{ item.type | default("replicated") }}
    {%- if item.type | default("replicated") == 'erasure' and item.erasure_profile != '' %}
    {{ item.erasure_profile }}
    {%- endif %}
    {{ item.expected_num_objects | default('') }}
  changed_when: false
  with_items: "{{ cephfs_pools }}"

- name: check if ceph filesystem already exists
  command: "{{docker_exec_cmd }} ceph --cluster {{ cluster }} fs get {{ cephfs }}"
  register: check_existing_cephfs
  changed_when: false
  failed_when: false

- name: create ceph filesystem
  command: "{{ docker_exec_cmd}} ceph --cluster {{ cluster }} fs new {{ cephfs }} {{ cephfs_metadata }} {{ cephfs_data }}"
  changed_when: false
  when:
    - check_existing_cephfs.rc != 0

- name: allow multimds
  command: "{{ docker_exec_cmd }} ceph --cluster {{ cluster }} fs set {{ cephfs }} allow_multimds true --yes-i-really-mean-it"
  changed_when: false
  when:
    - ceph_release_num[ceph_release] >= ceph_release_num.jewel
    - mds_allow_multimds

- name: set max_mds
  command: "{{ docker_exec_cmd }} ceph --cluster {{ cluster }} fs set {{ cephfs }} max_mds {{ mds_max_mds }}"
  changed_when: false
  when:
    - ceph_release_num[ceph_release] >= ceph_release_num.jewel
    - mds_allow_multimds
    - mds_max_mds > 1
